server:
  port: 8080

camunda.bpm:
  database:
    schema-update: true
    type: postgres
  admin-user:
    id: admin
    password: admin
  client:
    basic-auth:
      username: admin
      password: admin


spring:
  datasource:
    username: ${POSTGRES-USER}
    password: ${POSTGRES-PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    hibernate:
      ddl-auto: update


hibernate:
  dialect: org.hibernate.dialect.HSQLDialect