server:
  port: 8080

camunda.bpm:
  database:
    schema-update: true
    type: h2

camunda.bpm.admin-user:
  id: admin
  password: admin

spring:
  datasource:
    app:
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres

    camunda:
      jdbc-url: jdbc:h2:file:./camunda-h2-database
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto=update: update


hibernate:
  dialect: org.hibernate.dialect.HSQLDialect